# Generated by Django 4.2.6 on 2023-12-01 01:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_name", models.TextField()),
                ("role_description", models.TextField()),
                ("company_name", models.TextField()),
                ("company_description", models.TextField()),
                ("role_requirements", models.TextField()),
                ("location", models.TextField()),
                ("minimum_salary", models.PositiveIntegerField()),
                ("maximum_salary", models.PositiveIntegerField()),
            ],
        ),
    ]
