# Generated by Django 4.2.6 on 2023-12-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_crimescenereport_delete_job"),
    ]

    operations = [
        migrations.CreateModel(
            name="Suspect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("personal_id", models.IntegerField()),
                ("first_name", models.TextField()),
                ("last_name", models.TextField()),
                ("drivers_license_id", models.IntegerField()),
            ],
        ),
    ]
