# Generated by Django 4.2.6 on 2023-12-04 03:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_driverslicense"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DriversLicense",
        ),
    ]
